version: "3.8"
services:
  server:
    build: .
    ports:
      - 8080:8080
#    depends_on:
#      - mysqldb
#  mysqldb:
#    image: "mysql:5.7"
#    ports:
#      - 3307:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: esport2
